Remove unused import to fix build
> Assets/Scripts/HunterPlayerController.cs(4,19): error CS0234: The type or namespace name 'PackageManager' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)